# Generated by Django 4.1.4 on 2023-02-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0002_vendorcontactmodel_vendorloginmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsignupmodel',
            name='companyaddress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorsignupmodel',
            name='companyname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorsignupmodel',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorsignupmodel',
            name='fname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorsignupmodel',
            name='gender',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vendorsignupmodel',
            name='lname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorsignupmodel',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
