# Generated by Django 4.1.4 on 2023-02-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0004_categorymodel_subcategorymodel_productmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='VendorCategoryModel',
        ),
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='VendorProductModel',
        ),
        migrations.RenameModel(
            old_name='SubCategoryModel',
            new_name='VendorSubCategoryModel',
        ),
    ]
