# Generated by Django 4.1.4 on 2023-02-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0005_rename_categorymodel_vendorcategorymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOrderDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('subTotal', models.IntegerField()),
                ('gstPercentage', models.IntegerField()),
                ('gstAmount', models.FloatField()),
                ('deliveryCharge', models.IntegerField()),
                ('grantTotal', models.FloatField()),
                ('payment', models.CharField(max_length=20)),
                ('paymentVia', models.CharField(max_length=20)),
                ('transactionId', models.TextField()),
                ('orderStatus', models.CharField(default='Order Created', max_length=50)),
                ('orderDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
