# Generated by Django 4.1 on 2023-02-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0006_vendororderdetailsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorOrderDetailsModel',
        ),
        migrations.RemoveField(
            model_name='vendorproductmodel',
            name='subCategory',
        ),
        migrations.RemoveField(
            model_name='vendorsubcategorymodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='VendorCategoryModel',
        ),
        migrations.DeleteModel(
            name='VendorProductModel',
        ),
        migrations.DeleteModel(
            name='VendorSubCategoryModel',
        ),
    ]
