# Generated by Django 4.1.4 on 2023-01-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='image',
            field=models.ImageField(default='', upload_to='product/'),
        ),
    ]
