# Generated by Django 4.1.4 on 2023-02-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0003_remove_cartmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailsmodel',
            name='orderStatus',
            field=models.CharField(default='Order Created', max_length=50),
        ),
    ]
