# Generated by Django 4.1.4 on 2023-02-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0004_orderdetailsmodel_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodel',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
