# Generated by Django 4.1.4 on 2023-02-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0005_ratingmodel_rating_ratingmodel_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodel',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
