# Generated by Django 4.1 on 2023-02-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0007_ratingmodel_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderStatusTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=10)),
                ('deliveryDays', models.IntegerField()),
                ('trackingMessage', models.TextField()),
            ],
        ),
    ]
