# Generated by Django 4.1 on 2023-03-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0009_productmodel_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='vendorId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='vendorId',
            field=models.IntegerField(default=1),
        ),
    ]
