# Generated by Django 4.1 on 2023-03-08 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0007_delete_vendororderdetailsmodel_and_more'),
        ('CategoryApp', '0011_alter_productmodel_vendorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='vendorId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VendorApp.vendorsignupmodel'),
        ),
    ]
