# Generated by Django 4.1 on 2023-03-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0012_alter_cartmodel_vendorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='vendorId',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='vendorId',
            field=models.IntegerField(default=1),
        ),
    ]
