# Generated by Django 4.1.4 on 2023-02-07 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.CharField(max_length=100, validators=[django.core.validators.EmailValidator(message='Invalid Email')]),
        ),
    ]
